export const UniswapAmplifierABI = [
  {
    inputs: [
      { internalType: "address", name: "uniswapPool_", type: "address" },
      { internalType: "address", name: "zchf_", type: "address" },
      { internalType: "address", name: "zchfMinter_", type: "address" },
      { internalType: "uint40", name: "expiration", type: "uint40" },
      { internalType: "uint256", name: "borrowingLimit", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AccessDenied", type: "error" },
  { inputs: [], name: "AmplifierExpired", type: "error" },
  { inputs: [], name: "FailedDeployment", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "balance", type: "uint256" },
      { internalType: "uint256", name: "needed", type: "uint256" },
    ],
    name: "InsufficientBalance",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "requiredMinimum", type: "uint256" },
      {
        internalType: "uint256",
        name: "actuallyFoundInProvidedRange",
        type: "uint256",
      },
    ],
    name: "InsufficientDollarsInRange",
    type: "error",
  },
  {
    inputs: [
      { internalType: "int24", name: "min", type: "int24" },
      { internalType: "int24", name: "found", type: "int24" },
      { internalType: "int24", name: "max", type: "int24" },
    ],
    name: "InvalidTick",
    type: "error",
  },
  { inputs: [], name: "InvalidUniswapPool", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "newValue", type: "uint256" },
      { internalType: "uint256", name: "limit", type: "uint256" },
    ],
    name: "LimitExceeded",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "found", type: "uint256" },
      { internalType: "uint256", name: "expected", type: "uint256" },
    ],
    name: "PriceChangedTooMuch",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "SafeERC20FailedOperation",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "position",
        type: "address",
      },
    ],
    name: "AmplifiedPositionCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "borrowed",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalBorrowed",
        type: "uint256",
      },
    ],
    name: "Borrowed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalBorrowed",
        type: "uint256",
      },
    ],
    name: "Repaid",
    type: "event",
  },
  {
    inputs: [],
    name: "EXPIRATION",
    outputs: [{ internalType: "uint40", name: "", type: "uint40" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "LIMIT",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAXIMUM_TICK",
    outputs: [{ internalType: "int24", name: "", type: "int24" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_DOLLAR_APPRECIATION_TICKS",
    outputs: [{ internalType: "int24", name: "", type: "int24" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_DOLLAR_DEPRECIATION_TICKS",
    outputs: [{ internalType: "int24", name: "", type: "int24" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MINIMUM_TICK",
    outputs: [{ internalType: "int24", name: "", type: "int24" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PRICE_ANCHOR_X96",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "UNISWAP_POOL",
    outputs: [
      { internalType: "contract IUniswapV3Pool", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "USD",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ZCHF",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ZCHF_IS_TOKEN0",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ZCHF_MINTER",
    outputs: [
      {
        internalType: "contract IFrankencoinMinter",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "uint256", name: "token0Amount", type: "uint256" },
      { internalType: "uint256", name: "token1Amount", type: "uint256" },
    ],
    name: "borrowIntoPool",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "expectedPriceX96", type: "uint256" },
    ],
    name: "checkPrice",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "int24", name: "ticksLow", type: "int24" },
      { internalType: "int24", name: "ticksHigh", type: "int24" },
    ],
    name: "checkTicks",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "int24", name: "tickLow", type: "int24" },
      { internalType: "int24", name: "tickHigh", type: "int24" },
    ],
    name: "createAmplifiedPosition",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "exploitableAt",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "zchfAmount", type: "uint256" }],
    name: "getMinimumDollars",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPrice",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "positionCreationDate",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "positionImplementation",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "uint256", name: "borrowed", type: "uint256" },
      { internalType: "uint128", name: "returnedPart", type: "uint128" },
      { internalType: "uint128", name: "total", type: "uint128" },
    ],
    name: "repay",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalBorrowed",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
