name: CI
on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: Install packages
        run: npm i
      - name: Create dummy .env from .env.example
        run: mv .env.example .env
      - name: Run Tests
        run: npm test
